name: Semantic versioning

on:
    push:
        branches:
            - development

jobs:
    semantic-versioning:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # gives access to all previous commits
            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - name: Update version
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  npx standard-version
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN   }}
                  branch: ${{ github.ref   }}
